Story book
silwerlerman/Trello_Analog pull request #10
Opened 2023-12-17 15:58 UTC by silwerlerman

Добавлен StoryBook

2023-12-19 09:40 UTC, kglazkov commented
Ну и это соответственно буду смотреть после мержа предыдущего.

2023-12-29 09:04 UTC, kglazkov requested changes

2023-12-29 09:04 UTC, kglazkov commented on src/UI/Layout/HomePage/Stage/Stage.stories.tsx
> +const TaskLoaderDecorator = (Story: React.ComponentType): JSX.Element => {
Не очень понял зачем ты тут используешь react query для загрузки данных фейковых... Мне кажется это лишнее. Достаточно просто сгенерировать массив тасок и замапить его уже в необходимые компоненты в story без дополнительной логики с загрузкой.

2023-12-29 09:10 UTC, silwerlerman commented on src/UI/Layout/HomePage/Stage/Stage.stories.tsx
> +const TaskLoaderDecorator = (Story: React.ComponentType): JSX.Element => {
Там просто без query логика ломается и компонент не отображается, поэтому пришлось его подключить

2024-02-03 09:37 UTC, merged